export const BESTIARY_CONFIG = {
  MOUNTS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 1 } },
      { maxLevel: 100, count: { min: 1, max: 2 } },
      { maxLevel: 249, count: { min: 1, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 2 } },
      { maxLevel: 999, count: { min: 2, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 3 } },
      { maxLevel: Infinity, count: { min: 3, max: 4 } },
    ],
    MAX_TIER_BY_LEVEL: [
      { maxLevel: 10, tiers: [1] },
      { maxLevel: 25, tiers: [1] },
      { maxLevel: 50, tiers: [1, 2] },
      { maxLevel: 69, tiers: [1, 2, 2] },
      { maxLevel: 100, tiers: [2, 3] },
      { maxLevel: 249, tiers: [2, 3, 3] },
      { maxLevel: 499, tiers: [3, 4] },
      { maxLevel: 999, tiers: [4, 5] },
      { maxLevel: 2999, tiers: [4, 5, 6] },
      { maxLevel: Infinity, tiers: [5, 6, 6] },
    ],
  },
  MOUNT_BAGS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 1 } },
      { maxLevel: 100, count: { min: 1, max: 1 } },
      { maxLevel: 249, count: { min: 1, max: 1 } },
      { maxLevel: 499, count: { min: 1, max: 1 } },
      { maxLevel: 999, count: { min: 1, max: 1 } },
      { maxLevel: 2999, count: { min: 1, max: 1 } },
      { maxLevel: Infinity, count: { min: 1, max: 1 } },
    ],
  },
  PETS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 1, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 4 } },
      { maxLevel: Infinity, count: { min: 4, max: 5 } },
    ],
    MAX_TIER_BY_LEVEL: [
      { maxLevel: 10, tiers: [1] },
      { maxLevel: 25, tiers: [1] },
      { maxLevel: 50, tiers: [1, 2] },
      { maxLevel: 69, tiers: [1, 2, 2] },
      { maxLevel: 100, tiers: [2, 3] },
      { maxLevel: 249, tiers: [2, 3, 3] },
      { maxLevel: 499, tiers: [3, 4] },
      { maxLevel: 999, tiers: [4, 5] },
      { maxLevel: 2999, tiers: [4, 5, 6] },
      { maxLevel: Infinity, tiers: [5, 6, 6] },
    ],
  },
  SUMMONS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 1 } },
      { maxLevel: 100, count: { min: 1, max: 2 } },
      { maxLevel: 249, count: { min: 1, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 2 } },
      { maxLevel: 999, count: { min: 2, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 3 } },
      { maxLevel: Infinity, count: { min: 3, max: 4 } },
    ],
    ROLE_KEYWORDS: ['summoner', 'necromancer', 'druid', 'shaman', 'warlock', 'mage', 'wizard', 'cleric'],
    MAX_TIER_BY_LEVEL: [
      { maxLevel: 10, tiers: [1] },
      { maxLevel: 25, tiers: [1] },
      { maxLevel: 50, tiers: [1, 2] },
      { maxLevel: 69, tiers: [1, 2, 2] },
      { maxLevel: 100, tiers: [2, 3] },
      { maxLevel: 249, tiers: [2, 3, 3] },
      { maxLevel: 499, tiers: [3, 4] },
      { maxLevel: 999, tiers: [4, 5] },
      { maxLevel: 2999, tiers: [4, 5, 6] },
      { maxLevel: Infinity, tiers: [5, 6, 6] },
    ],
  },
} as const
