export const IDENTITY_CONFIG = {
  BONDS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 2, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 3 } },
      { maxLevel: 249, count: { min: 3, max: 3 } },
      { maxLevel: 499, count: { min: 3, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 4 } },
      { maxLevel: 2999, count: { min: 4, max: 5 } },
      { maxLevel: Infinity, count: { min: 5, max: 6 } },
    ],
  },
  QUIRKS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 2 } },
      { maxLevel: 50, count: { min: 1, max: 2 } },
      { maxLevel: 69, count: { min: 2, max: 3 } },
      { maxLevel: 100, count: { min: 3, max: 3 } },
      { maxLevel: 249, count: { min: 3, max: 4 } },
      { maxLevel: 499, count: { min: 4, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 5 } },
      { maxLevel: 2999, count: { min: 5, max: 6 } },
      { maxLevel: Infinity, count: { min: 6, max: 7 } },
    ],
  },
  SECRETS: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.16 },
      { maxLevel: 25, chance: 0.22 },
      { maxLevel: 50, chance: 0.32 },
      { maxLevel: 69, chance: 0.42 },
      { maxLevel: 100, chance: 0.52 },
      { maxLevel: 249, chance: 0.6 },
      { maxLevel: 499, chance: 0.68 },
      { maxLevel: 999, chance: 0.74 },
      { maxLevel: 2999, chance: 0.8 },
      { maxLevel: Infinity, chance: 0.88 },
    ],
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 1, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 4 } },
      { maxLevel: Infinity, count: { min: 4, max: 5 } },
    ],
  },
  PSYCHOLOGY: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.14 },
      { maxLevel: 25, chance: 0.2 },
      { maxLevel: 50, chance: 0.3 },
      { maxLevel: 69, chance: 0.4 },
      { maxLevel: 100, chance: 0.5 },
      { maxLevel: 249, chance: 0.57 },
      { maxLevel: 499, chance: 0.64 },
      { maxLevel: 999, chance: 0.7 },
      { maxLevel: 2999, chance: 0.77 },
      { maxLevel: Infinity, chance: 0.85 },
    ],
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 1, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 4 } },
      { maxLevel: Infinity, count: { min: 4, max: 5 } },
    ],
  },
  ATLAS: {
    POOL_LIMITS: {
      bonds: 6,
      quirks: 6,
      secrets: 6,
      psychologicalTraits: 6,
      variants: 3,
    },
  },
} as const
