export const INVENTORY_EXPANSION_CONFIG = {
  CURIOS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 2 } },
      { maxLevel: 69, count: { min: 2, max: 3 } },
      { maxLevel: 100, count: { min: 2, max: 3 } },
      { maxLevel: 249, count: { min: 3, max: 3 } },
      { maxLevel: 499, count: { min: 3, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 4 } },
      { maxLevel: 2999, count: { min: 4, max: 5 } },
      { maxLevel: Infinity, count: { min: 5, max: 6 } },
    ],
  },
  CUISINE: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 2 } },
      { maxLevel: 69, count: { min: 2, max: 3 } },
      { maxLevel: 100, count: { min: 3, max: 3 } },
      { maxLevel: 249, count: { min: 3, max: 4 } },
      { maxLevel: 499, count: { min: 3, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 5 } },
      { maxLevel: 2999, count: { min: 4, max: 6 } },
      { maxLevel: Infinity, count: { min: 5, max: 7 } },
    ],
    ROLE_TYPE_WEIGHTS: [
      { keywords: ['ranger', 'druid', 'hunter', 'scout', 'warden'], types: ['Ration', 'Campfire', 'Preserve'], weight: 3 },
      { keywords: ['alchemist', 'mage', 'wizard', 'warlock', 'witch'], types: ['Alchemical', 'Beverage'], weight: 3 },
      { keywords: ['rogue', 'thief', 'assassin', 'bard'], types: ['Street Food', 'Beverage', 'Delicacy'], weight: 2.4 },
      { keywords: ['fighter', 'warrior', 'knight', 'paladin', 'berserker'], types: ['Tavern Fare', 'Ration', 'Monster Fare'], weight: 2.6 },
    ],
  },
  ENCHANTMENTS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 4 } },
      { maxLevel: Infinity, count: { min: 4, max: 5 } },
    ],
    MAX_RARITY_BY_LEVEL: [
      { maxLevel: 10, rarities: ['Common'] },
      { maxLevel: 25, rarities: ['Common'] },
      { maxLevel: 50, rarities: ['Common', 'Uncommon'] },
      { maxLevel: 69, rarities: ['Common', 'Uncommon', 'Uncommon'] },
      { maxLevel: 100, rarities: ['Uncommon', 'Rare'] },
      { maxLevel: 249, rarities: ['Uncommon', 'Rare', 'Rare'] },
      { maxLevel: 499, rarities: ['Rare', 'Epic'] },
      { maxLevel: 999, rarities: ['Epic', 'Legendary'] },
      { maxLevel: 2999, rarities: ['Epic', 'Legendary', 'Mythic'] },
      { maxLevel: Infinity, rarities: ['Legendary', 'Mythic', 'Mythic'] },
    ],
    ROLE_TARGET_WEIGHTS: [
      { keywords: ['fighter', 'warrior', 'rogue', 'assassin', 'ranger', 'samurai'], targets: ['Weapon'], weight: 3 },
      { keywords: ['knight', 'paladin', 'guardian', 'warden', 'cleric'], targets: ['Armor', 'Shield'], weight: 3 },
      { keywords: ['mage', 'wizard', 'warlock', 'sorcerer', 'witch', 'bard'], targets: ['Accessory'], weight: 3 },
    ],
  },
  INSTRUMENTS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 3 } },
      { maxLevel: 2999, count: { min: 3, max: 4 } },
      { maxLevel: Infinity, count: { min: 4, max: 5 } },
    ],
    ROLE_CATEGORY_WEIGHTS: [
      { keywords: ['bard', 'minstrel', 'performer'], categories: ['String', 'Wind', 'Percussion', 'Keyboard'], weight: 4 },
      { keywords: ['rogue', 'thief', 'assassin', 'spy'], categories: ['Tool', 'Wind'], weight: 2.6 },
      { keywords: ['mage', 'wizard', 'scribe', 'artificer'], categories: ['Tool', 'Keyboard'], weight: 2.4 },
    ],
  },
  MERCHANDISE: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 2 } },
      { maxLevel: 69, count: { min: 2, max: 3 } },
      { maxLevel: 100, count: { min: 3, max: 3 } },
      { maxLevel: 249, count: { min: 3, max: 4 } },
      { maxLevel: 499, count: { min: 3, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 5 } },
      { maxLevel: 2999, count: { min: 4, max: 6 } },
      { maxLevel: Infinity, count: { min: 5, max: 7 } },
    ],
    ROLE_CATEGORY_WEIGHTS: [
      { keywords: ['merchant', 'trader', 'noble', 'bard'], categories: ['Trade Good', 'Gemstone', 'Art Object'], weight: 3 },
      { keywords: ['rogue', 'thief', 'assassin', 'smuggler'], categories: ['Contraband', 'Curiosity'], weight: 3 },
      { keywords: ['scholar', 'mage', 'wizard', 'artificer'], categories: ['Curiosity', 'Gemstone', 'Art Object'], weight: 2.6 },
    ],
  },
  RECIPES: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 2 } },
      { maxLevel: 69, count: { min: 2, max: 3 } },
      { maxLevel: 100, count: { min: 3, max: 4 } },
      { maxLevel: 249, count: { min: 3, max: 4 } },
      { maxLevel: 499, count: { min: 4, max: 5 } },
      { maxLevel: 999, count: { min: 4, max: 6 } },
      { maxLevel: 2999, count: { min: 5, max: 7 } },
      { maxLevel: Infinity, count: { min: 6, max: 8 } },
    ],
    MIN_DIFFICULTY_BY_LEVEL: [
      { maxLevel: 10, difficultyModifiers: [-1] },
      { maxLevel: 25, difficultyModifiers: [-1, -2] },
      { maxLevel: 50, difficultyModifiers: [-2, -3] },
      { maxLevel: 69, difficultyModifiers: [-2, -3, -3] },
      { maxLevel: 100, difficultyModifiers: [-3, -4] },
      { maxLevel: 249, difficultyModifiers: [-4, -5] },
      { maxLevel: 499, difficultyModifiers: [-5, -6] },
      { maxLevel: 999, difficultyModifiers: [-6, -7] },
      { maxLevel: 2999, difficultyModifiers: [-7, -8, -9] },
      { maxLevel: Infinity, difficultyModifiers: [-8, -9, -9] },
    ],
    ROLE_CATEGORY_WEIGHTS: [
      { keywords: ['alchemist', 'chemist', 'witch', 'healer'], categories: ['Alchemy'], weight: 4 },
      { keywords: ['smith', 'fighter', 'warrior', 'knight', 'paladin'], categories: ['Weapon', 'Armor'], weight: 3 },
      { keywords: ['mage', 'wizard', 'warlock', 'sorcerer'], categories: ['Enchanting', 'Alchemy'], weight: 3.4 },
      { keywords: ['ranger', 'druid', 'hunter', 'scout'], categories: ['Cooking', 'Tool'], weight: 2.8 },
      { keywords: ['rogue', 'thief', 'assassin', 'artificer'], categories: ['Tool', 'Alchemy'], weight: 2.6 },
    ],
  },
} as const
