export const MAGIC_CONFIG = {
  SPELLS: {
    CASTER_ROLE_KEYWORDS: [
      'mage',
      'wizard',
      'sorcerer',
      'warlock',
      'witch',
      'cleric',
      'priest',
      'druid',
      'shaman',
      'necromancer',
      'summoner',
      'alchemist',
      'enchanter',
      'oracle',
      'bard',
    ],
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 0, max: 2 } },
      { maxLevel: 25, count: { min: 2, max: 3 } },
      { maxLevel: 50, count: { min: 2, max: 4 } },
      { maxLevel: 69, count: { min: 3, max: 5 } },
      { maxLevel: 100, count: { min: 4, max: 6 } },
      { maxLevel: 249, count: { min: 7, max: 9 } },
      { maxLevel: 499, count: { min: 9, max: 11 } },
      { maxLevel: 999, count: { min: 10, max: 14 } },
      { maxLevel: 2999, count: { min: 15, max: 19 } },
      { maxLevel: Infinity, count: { min: 18, max: 22 } },
    ],
    NON_CASTER_MAX_COUNT: 1,
    LEVEL_ORDER: ['Petty', 'Novice', 'Adept', 'Master'],
    SKILL_RANK_BY_LEVEL_AND_RARITY: {
      Petty: { Common: 'F', Uncommon: 'E', Rare: 'D', Legendary: 'C' },
      Novice: { Common: 'C', Uncommon: 'B', Rare: 'A', Legendary: 'S' },
      Adept: { Common: 'A', Uncommon: 'S', Rare: 'SS', Legendary: 'SSS' },
      Master: { Common: 'SS', Uncommon: 'SSS', Rare: 'SSSS', Legendary: 'Legendary' },
    },
    MAX_SPELL_LEVEL_BY_CHARACTER_LEVEL: [
      { maxLevel: 10, spellLevels: ['Petty'] },
      { maxLevel: 25, spellLevels: ['Petty'] },
      { maxLevel: 50, spellLevels: ['Petty', 'Novice'] },
      { maxLevel: 69, spellLevels: ['Petty', 'Novice', 'Novice'] },
      { maxLevel: 100, spellLevels: ['Novice', 'Adept'] },
      { maxLevel: 249, spellLevels: ['Novice', 'Adept', 'Adept'] },
      { maxLevel: 499, spellLevels: ['Adept', 'Master'] },
      { maxLevel: 999, spellLevels: ['Adept', 'Master', 'Master'] },
      { maxLevel: 2999, spellLevels: ['Adept', 'Master', 'Master'] },
      { maxLevel: Infinity, spellLevels: ['Adept', 'Master', 'Master', 'Master'] },
    ],
  },
  HAZARDS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 0, max: 0 } },
      { maxLevel: 25, count: { min: 0, max: 0 } },
      { maxLevel: 50, count: { min: 0, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 1, max: 2 } },
      { maxLevel: 249, count: { min: 1, max: 2 } },
      { maxLevel: 499, count: { min: 2, max: 2 } },
      { maxLevel: 999, count: { min: 2, max: 3 } },
      { maxLevel: 2999, count: { min: 2, max: 3 } },
      { maxLevel: Infinity, count: { min: 3, max: 4 } },
    ],
  },
} as const
