export const MECHANICS_CONFIG = {
  FEATS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 2 } },
      { maxLevel: 69, count: { min: 2, max: 3 } },
      { maxLevel: 100, count: { min: 3, max: 4 } },
      { maxLevel: 249, count: { min: 3, max: 4 } },
      { maxLevel: 499, count: { min: 4, max: 5 } },
      { maxLevel: 999, count: { min: 5, max: 6 } },
      { maxLevel: 2999, count: { min: 6, max: 8 } },
      { maxLevel: Infinity, count: { min: 8, max: 10 } },
    ],
    MAX_TIER_BY_LEVEL: [
      { maxLevel: 10, tiers: [1] },
      { maxLevel: 25, tiers: [1] },
      { maxLevel: 50, tiers: [1] },
      { maxLevel: 69, tiers: [1, 2] },
      { maxLevel: 100, tiers: [1, 2, 2] },
      { maxLevel: 249, tiers: [1, 2, 2] },
      { maxLevel: 499, tiers: [2, 3] },
      { maxLevel: 999, tiers: [2, 3, 3] },
      { maxLevel: 2999, tiers: [2, 3, 3] },
      { maxLevel: Infinity, tiers: [2, 3, 3, 3] },
    ],
  },
  ACHIEVEMENTS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 0, max: 0 } },
      { maxLevel: 25, count: { min: 0, max: 0 } },
      { maxLevel: 50, count: { min: 0, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 3 } },
      { maxLevel: 499, count: { min: 3, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 5 } },
      { maxLevel: 2999, count: { min: 5, max: 7 } },
      { maxLevel: Infinity, count: { min: 6, max: 9 } },
    ],
  },
  AFFLICTIONS: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.08 },
      { maxLevel: 25, chance: 0.12 },
      { maxLevel: 50, chance: 0.16 },
      { maxLevel: 69, chance: 0.2 },
      { maxLevel: 100, chance: 0.24 },
      { maxLevel: 249, chance: 0.28 },
      { maxLevel: 499, chance: 0.32 },
      { maxLevel: 999, chance: 0.37 },
      { maxLevel: 2999, chance: 0.42 },
      { maxLevel: Infinity, chance: 0.5 },
    ],
  },
  CRIMES: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.08 },
      { maxLevel: 25, chance: 0.12 },
      { maxLevel: 50, chance: 0.17 },
      { maxLevel: 69, chance: 0.22 },
      { maxLevel: 100, chance: 0.27 },
      { maxLevel: 249, chance: 0.32 },
      { maxLevel: 499, chance: 0.36 },
      { maxLevel: 999, chance: 0.43 },
      { maxLevel: 2999, chance: 0.5 },
      { maxLevel: Infinity, chance: 0.6 },
    ],
  },
  MARTIAL_ARTS: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.08 },
      { maxLevel: 25, chance: 0.12 },
      { maxLevel: 50, chance: 0.18 },
      { maxLevel: 69, chance: 0.24 },
      { maxLevel: 100, chance: 0.32 },
      { maxLevel: 249, chance: 0.38 },
      { maxLevel: 499, chance: 0.44 },
      { maxLevel: 999, chance: 0.53 },
      { maxLevel: 2999, chance: 0.62 },
      { maxLevel: Infinity, chance: 0.75 },
    ],
    ROLE_KEYWORDS: ['monk', 'fighter', 'warrior', 'knight', 'samurai', 'ninja', 'assassin', 'brawler', 'duelist'],
  },
} as const
