export const WORLD_CONFIG = {
  LANGUAGES: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 1, max: 1 } },
      { maxLevel: 25, count: { min: 1, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 2, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 3 } },
      { maxLevel: 249, count: { min: 3, max: 3 } },
      { maxLevel: 499, count: { min: 3, max: 4 } },
      { maxLevel: 999, count: { min: 4, max: 5 } },
      { maxLevel: 2999, count: { min: 5, max: 6 } },
      { maxLevel: Infinity, count: { min: 5, max: 6 } },
    ],
  },
  DEITIES: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.24 },
      { maxLevel: 25, chance: 0.3 },
      { maxLevel: 50, chance: 0.38 },
      { maxLevel: 69, chance: 0.45 },
      { maxLevel: 100, chance: 0.52 },
      { maxLevel: 249, chance: 0.58 },
      { maxLevel: 499, chance: 0.64 },
      { maxLevel: 999, chance: 0.7 },
      { maxLevel: 2999, chance: 0.78 },
      { maxLevel: Infinity, chance: 0.86 },
    ],
  },
  CUSTOMS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 0, max: 1 } },
      { maxLevel: 25, count: { min: 0, max: 1 } },
      { maxLevel: 50, count: { min: 1, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 3 } },
      { maxLevel: 499, count: { min: 3, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 4 } },
      { maxLevel: 2999, count: { min: 4, max: 5 } },
      { maxLevel: Infinity, count: { min: 5, max: 6 } },
    ],
  },
  LANDMARKS: {
    COUNT_BY_LEVEL: [
      { maxLevel: 10, count: { min: 0, max: 0 } },
      { maxLevel: 25, count: { min: 0, max: 0 } },
      { maxLevel: 50, count: { min: 0, max: 1 } },
      { maxLevel: 69, count: { min: 1, max: 2 } },
      { maxLevel: 100, count: { min: 2, max: 2 } },
      { maxLevel: 249, count: { min: 2, max: 3 } },
      { maxLevel: 499, count: { min: 3, max: 3 } },
      { maxLevel: 999, count: { min: 3, max: 4 } },
      { maxLevel: 2999, count: { min: 4, max: 5 } },
      { maxLevel: Infinity, count: { min: 5, max: 6 } },
    ],
  },
  HISTORY: {
    CHANCE_BY_LEVEL: [
      { maxLevel: 10, chance: 0.18 },
      { maxLevel: 25, chance: 0.25 },
      { maxLevel: 50, chance: 0.32 },
      { maxLevel: 69, chance: 0.38 },
      { maxLevel: 100, chance: 0.5 },
      { maxLevel: 249, chance: 0.58 },
      { maxLevel: 499, chance: 0.65 },
      { maxLevel: 999, chance: 0.72 },
      { maxLevel: 2999, chance: 0.8 },
      { maxLevel: Infinity, chance: 0.9 },
    ],
    SOURCE_REVEAL_BY_LEVEL: [
      { maxLevel: 10, chance: 0.9, count: { min: 1, max: 1 }, fallbackCount: { min: 2, max: 2 } },
      { maxLevel: 25, chance: 0.88, count: { min: 1, max: 1 }, fallbackCount: { min: 2, max: 2 } },
      { maxLevel: 50, chance: 0.84, count: { min: 1, max: 1 }, fallbackCount: { min: 2, max: 3 } },
      { maxLevel: 69, chance: 0.8, count: { min: 1, max: 2 }, fallbackCount: { min: 2, max: 3 } },
      { maxLevel: 100, chance: 0.76, count: { min: 2, max: 2 }, fallbackCount: { min: 3, max: 3 } },
      { maxLevel: 249, chance: 0.72, count: { min: 2, max: 3 }, fallbackCount: { min: 3, max: 4 } },
      { maxLevel: 499, chance: 0.68, count: { min: 2, max: 3 }, fallbackCount: { min: 3, max: 4 } },
      { maxLevel: 999, chance: 0.64, count: { min: 3, max: 3 }, fallbackCount: { min: 4, max: 4 } },
      { maxLevel: 2999, chance: 0.6, count: { min: 3, max: 4 }, fallbackCount: { min: 4, max: 5 } },
      { maxLevel: Infinity, chance: 0.56, count: { min: 4, max: 5 }, fallbackCount: { min: 5, max: 6 } },
    ],
  },
  ATLAS: {
    POOL_LIMITS: {
      homeRegions: 5,
      regionGuilds: 5,
      factions: 5,
      languages: 3,
      customs: 2,
      customVariations: 1,
      deities: 4,
      history: 4,
      landmarks: 5,
    },
  },
} as const
